DELETE FROM "aigc_model_provider";
DELETE FROM "aigc_model_usage_log";
DELETE FROM "aigc_model";
DELETE FROM "aigc_model_channel";
DELETE FROM "aigc_model_capability";
DELETE FROM "aigc_model_param_template";
DELETE FROM "aigc_model_price";
DELETE FROM "aigc_model_route";
DELETE FROM "aigc_model_tenant";
