CREATE TABLE IF NOT EXISTS "aigc_model_provider" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "code" varchar(64) NOT NULL,
    "name" varchar(128) NOT NULL,
    "api_base_url" varchar(512) NOT NULL,
    "auth_type" varchar(32) NOT NULL,
    "api_key" varchar(1024),
    "secret_key" varchar(1024),
    "extra_config" varchar(4096),
    "timeout_seconds" int DEFAULT 30,
    "proxy_enabled" bit DEFAULT FALSE,
    "proxy_id" bigint,
    "proxy_protocol" varchar(32),
    "proxy_host" varchar(255),
    "proxy_port" int,
    "proxy_username" varchar(255),
    "proxy_password" varchar(1024),
    "rate_limit_config" varchar(4096),
    "health_status" varchar(32) DEFAULT 'UNKNOWN',
    "balance" decimal(18,6) DEFAULT 0,
    "status" int NOT NULL DEFAULT 1,
    "remark" varchar(512),
    "tenant_id" bigint NOT NULL DEFAULT 0,
    "creator" varchar(64) DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "aigc_model_proxy" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(128) NOT NULL,
    "protocol" varchar(32) NOT NULL,
    "host" varchar(255) NOT NULL,
    "port" int NOT NULL,
    "username" varchar(255),
    "password" varchar(1024),
    "status" int NOT NULL DEFAULT 0,
    "remark" varchar(512),
    "tenant_id" bigint NOT NULL DEFAULT 0,
    "creator" varchar(64) DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "aigc_model" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "provider_id" bigint NOT NULL,
    "code" varchar(64) NOT NULL,
    "name" varchar(128) NOT NULL,
    "model" varchar(128) NOT NULL,
    "type" int NOT NULL,
    "public_visible" bit DEFAULT FALSE,
    "default_model" bit DEFAULT FALSE,
    "sort" int DEFAULT 0,
    "max_concurrent" int DEFAULT 10,
    "timeout_seconds" int DEFAULT 60,
    "queue_priority" int DEFAULT 100,
    "status" int NOT NULL DEFAULT 1,
    "remark" varchar(512),
    "creator" varchar(64) DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "aigc_model_capability" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "model_id" bigint NOT NULL,
    "capability" varchar(64) NOT NULL,
    "status" int DEFAULT 1,
    "remark" varchar(512),
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "aigc_model_param_template" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "model_id" bigint NOT NULL,
    "capability" varchar(64) NOT NULL,
    "param_key" varchar(64) NOT NULL,
    "param_name" varchar(128) NOT NULL,
    "param_type" varchar(32) NOT NULL,
    "required_status" bit DEFAULT FALSE,
    "default_value" varchar(512),
    "options" varchar(4096),
    "min_value" decimal(18,6),
    "max_value" decimal(18,6),
    "regex_pattern" varchar(512),
    "sort" int DEFAULT 0,
    "status" int DEFAULT 1,
    "creator" varchar(64) DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "aigc_model_price" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "model_id" bigint NOT NULL,
    "capability" varchar(64) NOT NULL,
    "billing_unit" varchar(32) NOT NULL,
    "cost_price" decimal(18,6) NOT NULL DEFAULT 0,
    "sale_price" decimal(18,6) NOT NULL DEFAULT 0,
    "currency_type" varchar(32) DEFAULT 'POINT',
    "price_config" varchar(4096),
    "effective_start_time" datetime,
    "effective_end_time" datetime,
    "status" int DEFAULT 1,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    "creator" varchar(64) DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "uk_model_capability_tenant" ON "aigc_model_price" ("model_id", "capability", "tenant_id");

CREATE TABLE IF NOT EXISTS "aigc_model_route" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(128) NOT NULL,
    "task_type" varchar(64),
    "capability" varchar(64),
    "strategy" varchar(64) NOT NULL,
    "model_ids" varchar(4096),
    "user_level" varchar(64),
    "status" int DEFAULT 1,
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "aigc_model_tenant" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id" bigint NOT NULL,
    "model_id" bigint NOT NULL,
    "enabled" bit DEFAULT TRUE,
    "public_visible" bit DEFAULT FALSE,
    "default_model" bit DEFAULT FALSE,
    "sort" int DEFAULT 0,
    "max_concurrent" int,
    "daily_limit" int,
    "remark" varchar(512),
    "creator" varchar(64) DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
);
