CREATE TABLE IF NOT EXISTS `aigc_asset` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `asset_no` varchar(64) NOT NULL,
  `user_id` bigint NOT NULL,
  `asset_type` varchar(32) NOT NULL,
  `source_type` varchar(32) NOT NULL,
  `biz_type` varchar(64) DEFAULT NULL,
  `biz_id` varchar(128) DEFAULT NULL,
  `task_id` bigint DEFAULT NULL,
  `task_no` varchar(64) DEFAULT NULL,
  `model_id` bigint DEFAULT NULL,
  `provider_id` bigint DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  `description` varchar(1024) DEFAULT NULL,
  `tags` varchar(512) DEFAULT NULL,
  `file_id` bigint DEFAULT NULL,
  `file_url` varchar(1024) NOT NULL,
  `origin_url` varchar(1024) DEFAULT NULL,
  `cover_file_id` bigint DEFAULT NULL,
  `cover_url` varchar(1024) DEFAULT NULL,
  `thumbnail_url` varchar(1024) DEFAULT NULL,
  `mime_type` varchar(128) DEFAULT NULL,
  `file_ext` varchar(32) DEFAULT NULL,
  `file_size` bigint DEFAULT NULL,
  `width` int DEFAULT NULL,
  `height` int DEFAULT NULL,
  `duration` decimal(18,3) DEFAULT NULL,
  `metadata` varchar(4096) DEFAULT NULL,
  `prompt_snapshot` varchar(4096) DEFAULT NULL,
  `generate_snapshot` varchar(4096) DEFAULT NULL,
  `visibility` varchar(32) NOT NULL,
  `audit_status` varchar(32) NOT NULL,
  `audit_reason` varchar(512) DEFAULT NULL,
  `status` varchar(32) NOT NULL,
  `view_count` int NOT NULL DEFAULT 0,
  `download_count` int NOT NULL DEFAULT 0,
  `use_count` int NOT NULL DEFAULT 0,
  `last_used_time` datetime DEFAULT NULL,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted` bit NOT NULL DEFAULT 0,
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_asset_no` (`asset_no`),
  UNIQUE KEY `uk_task_type_tenant` (`task_id`, `asset_type`, `tenant_id`)
);

CREATE TABLE IF NOT EXISTS `aigc_asset_download_log` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `asset_id` bigint NOT NULL,
  `asset_no` varchar(64) NOT NULL,
  `user_id` bigint DEFAULT NULL,
  `owner_user_id` bigint NOT NULL,
  `download_url` varchar(1024) DEFAULT NULL,
  `client_ip` varchar(64) DEFAULT NULL,
  `user_agent` varchar(512) DEFAULT NULL,
  `referer` varchar(512) DEFAULT NULL,
  `result` varchar(32) NOT NULL,
  `fail_reason` varchar(512) DEFAULT NULL,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted` bit NOT NULL DEFAULT 0,
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
);
