CREATE TABLE IF NOT EXISTS `aigc_workflow_definition` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `name` varchar(128) NOT NULL COMMENT '工作流名称',
  `code` varchar(128) NOT NULL COMMENT '工作流编码',
  `description` varchar(1024) DEFAULT NULL COMMENT '描述',
  `cover_url` varchar(1024) DEFAULT NULL COMMENT '封面',
  `category_id` bigint DEFAULT NULL COMMENT '分类',
  `visibility` varchar(32) NOT NULL COMMENT '可见性',
  `status` varchar(32) NOT NULL COMMENT '状态',
  `current_version_id` bigint DEFAULT NULL COMMENT '当前版本',
  `input_schema` json DEFAULT NULL COMMENT '输入参数 Schema',
  `output_schema` json DEFAULT NULL COMMENT '输出参数 Schema',
  `config` json DEFAULT NULL COMMENT '工作流配置',
  `creator_user_id` bigint DEFAULT NULL COMMENT '创建用户',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_code` (`tenant_id`, `code`),
  KEY `idx_tenant_status` (`tenant_id`, `status`),
  KEY `idx_tenant_category` (`tenant_id`, `category_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AIGC 工作流定义表';

CREATE TABLE IF NOT EXISTS `aigc_workflow_node` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `workflow_id` bigint NOT NULL COMMENT '工作流 ID',
  `version_id` bigint DEFAULT NULL COMMENT '版本 ID',
  `node_key` varchar(128) NOT NULL COMMENT '节点唯一键',
  `node_name` varchar(128) DEFAULT NULL COMMENT '节点名称',
  `node_type` varchar(64) NOT NULL COMMENT '节点类型',
  `generate_type` varchar(64) DEFAULT NULL COMMENT '生成类型',
  `generate_mode` varchar(64) DEFAULT NULL COMMENT '生成模式',
  `model_id` bigint DEFAULT NULL COMMENT '默认模型',
  `input_mapping` json DEFAULT NULL COMMENT '入参映射',
  `output_mapping` json DEFAULT NULL COMMENT '出参映射',
  `param_config` json DEFAULT NULL COMMENT '节点参数',
  `retry_config` json DEFAULT NULL COMMENT '重试配置',
  `timeout_seconds` int DEFAULT NULL COMMENT '超时时间',
  `position` json DEFAULT NULL COMMENT '前端画布位置',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_version_node` (`workflow_id`, `version_id`, `node_key`, `tenant_id`),
  KEY `idx_workflow_version` (`workflow_id`, `version_id`),
  KEY `idx_node_type` (`node_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AIGC 工作流节点定义表';

CREATE TABLE IF NOT EXISTS `aigc_workflow_edge` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `workflow_id` bigint NOT NULL COMMENT '工作流 ID',
  `version_id` bigint DEFAULT NULL COMMENT '版本 ID',
  `edge_key` varchar(128) NOT NULL COMMENT '边唯一键',
  `source_node_key` varchar(128) NOT NULL COMMENT '上游节点',
  `target_node_key` varchar(128) NOT NULL COMMENT '下游节点',
  `condition_config` json DEFAULT NULL COMMENT '条件配置',
  `input_mapping` json DEFAULT NULL COMMENT '入参映射',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_version_edge` (`workflow_id`, `version_id`, `edge_key`, `tenant_id`),
  KEY `idx_workflow_version` (`workflow_id`, `version_id`),
  KEY `idx_source_target` (`source_node_key`, `target_node_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AIGC 工作流边关系表';

CREATE TABLE IF NOT EXISTS `aigc_workflow_version` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `workflow_id` bigint NOT NULL COMMENT '工作流 ID',
  `version_no` int NOT NULL COMMENT '版本号',
  `version_name` varchar(128) DEFAULT NULL COMMENT '版本名称',
  `definition_snapshot` json DEFAULT NULL COMMENT '定义快照',
  `node_snapshot` json DEFAULT NULL COMMENT '节点快照',
  `edge_snapshot` json DEFAULT NULL COMMENT '边快照',
  `status` varchar(32) NOT NULL COMMENT '状态',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_workflow_version` (`workflow_id`, `version_no`, `tenant_id`),
  KEY `idx_workflow_status` (`workflow_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AIGC 工作流版本表';

CREATE TABLE IF NOT EXISTS `aigc_workflow_instance` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `instance_no` varchar(64) NOT NULL COMMENT '实例编号',
  `workflow_id` bigint NOT NULL COMMENT '工作流 ID',
  `workflow_version_id` bigint DEFAULT NULL COMMENT '工作流版本 ID',
  `template_id` bigint DEFAULT NULL COMMENT '来源模板',
  `user_id` bigint NOT NULL COMMENT '用户 ID',
  `status` varchar(32) NOT NULL COMMENT '状态',
  `input_data` json DEFAULT NULL COMMENT '输入数据',
  `output_data` json DEFAULT NULL COMMENT '输出数据',
  `main_task_id` bigint DEFAULT NULL COMMENT '主任务 ID',
  `freeze_id` bigint DEFAULT NULL COMMENT '计费冻结 ID',
  `estimate_amount` bigint DEFAULT NULL COMMENT '预估费用',
  `actual_amount` bigint DEFAULT NULL COMMENT '实际费用',
  `progress` int NOT NULL DEFAULT 0 COMMENT '进度',
  `fail_reason` varchar(512) DEFAULT NULL COMMENT '失败原因',
  `fail_message` varchar(2048) DEFAULT NULL COMMENT '失败详情',
  `start_time` datetime DEFAULT NULL COMMENT '开始时间',
  `finish_time` datetime DEFAULT NULL COMMENT '结束时间',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_instance_no` (`tenant_id`, `instance_no`),
  KEY `idx_user_status` (`tenant_id`, `user_id`, `status`),
  KEY `idx_workflow_status` (`workflow_id`, `status`),
  KEY `idx_main_task` (`main_task_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AIGC 工作流实例表';

CREATE TABLE IF NOT EXISTS `aigc_workflow_node_instance` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `workflow_instance_id` bigint NOT NULL COMMENT '工作流实例',
  `node_id` bigint DEFAULT NULL COMMENT '节点定义',
  `node_key` varchar(128) NOT NULL COMMENT '节点键',
  `node_type` varchar(64) NOT NULL COMMENT '节点类型',
  `status` varchar(32) NOT NULL COMMENT '状态',
  `task_id` bigint DEFAULT NULL COMMENT '关联任务 ID',
  `gen_record_id` bigint DEFAULT NULL COMMENT '生成记录 ID',
  `input_data` json DEFAULT NULL COMMENT '节点入参',
  `output_data` json DEFAULT NULL COMMENT '节点出参',
  `asset_ids` json DEFAULT NULL COMMENT '输出资产',
  `retry_count` int NOT NULL DEFAULT 0 COMMENT '重试次数',
  `max_retry_count` int NOT NULL DEFAULT 0 COMMENT '最大重试次数',
  `cost_amount` bigint DEFAULT NULL COMMENT '节点费用',
  `start_time` datetime DEFAULT NULL COMMENT '开始时间',
  `finish_time` datetime DEFAULT NULL COMMENT '结束时间',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_instance_node` (`workflow_instance_id`, `node_key`, `tenant_id`),
  KEY `idx_instance_status` (`workflow_instance_id`, `status`),
  KEY `idx_task_id` (`task_id`),
  KEY `idx_gen_record_id` (`gen_record_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AIGC 工作流节点实例表';

CREATE TABLE IF NOT EXISTS `aigc_workflow_log` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `workflow_instance_id` bigint NOT NULL COMMENT '工作流实例',
  `node_instance_id` bigint DEFAULT NULL COMMENT '节点实例',
  `log_type` varchar(64) NOT NULL COMMENT '日志类型',
  `from_status` varchar(32) DEFAULT NULL COMMENT '原状态',
  `to_status` varchar(32) DEFAULT NULL COMMENT '目标状态',
  `summary` varchar(512) DEFAULT NULL COMMENT '摘要',
  `detail_data` json DEFAULT NULL COMMENT '详情 JSON',
  `cost_millis` bigint DEFAULT NULL COMMENT '耗时毫秒',
  `user_id` bigint DEFAULT NULL COMMENT '用户 ID',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  KEY `idx_instance_node` (`workflow_instance_id`, `node_instance_id`),
  KEY `idx_user_time` (`user_id`, `create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AIGC 工作流日志表';
