CREATE TABLE IF NOT EXISTS `aigc_workflow_definition` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `name` varchar(128) NOT NULL COMMENT '工作流名称',
  `code` varchar(128) NOT NULL COMMENT '工作流编码',
  `description` varchar(1024) DEFAULT NULL COMMENT '描述',
  `cover_url` varchar(1024) DEFAULT NULL COMMENT '封面',
  `category_id` bigint DEFAULT NULL COMMENT '分类',
  `visibility` varchar(32) NOT NULL COMMENT '可见性',
  `status` varchar(32) NOT NULL COMMENT '状态',
  `current_version_id` bigint DEFAULT NULL COMMENT '当前版本',
  `input_schema` json DEFAULT NULL COMMENT '输入参数 Schema',
  `output_schema` json DEFAULT NULL COMMENT '输出参数 Schema',
  `config` json DEFAULT NULL COMMENT '工作流配置',
  `creator_user_id` bigint DEFAULT NULL COMMENT '创建用户',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_code` (`tenant_id`, `code`),
  KEY `idx_tenant_status` (`tenant_id`, `status`),
  KEY `idx_tenant_category` (`tenant_id`, `category_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AIGC 工作流定义表';

CREATE TABLE IF NOT EXISTS `aigc_workflow_node` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `workflow_id` bigint NOT NULL COMMENT '工作流 ID',
  `version_id` bigint DEFAULT NULL COMMENT '版本 ID',
  `node_key` varchar(128) NOT NULL COMMENT '节点唯一键',
  `node_name` varchar(128) DEFAULT NULL COMMENT '节点名称',
  `node_type` varchar(64) NOT NULL COMMENT '节点类型',
  `generate_type` varchar(64) DEFAULT NULL COMMENT '生成类型',
  `generate_mode` varchar(64) DEFAULT NULL COMMENT '生成模式',
  `model_id` bigint DEFAULT NULL COMMENT '默认模型',
  `input_mapping` json DEFAULT NULL COMMENT '入参映射',
  `output_mapping` json DEFAULT NULL COMMENT '出参映射',
  `param_config` json DEFAULT NULL COMMENT '节点参数',
  `retry_config` json DEFAULT NULL COMMENT '重试配置',
  `timeout_seconds` int DEFAULT NULL COMMENT '超时时间',
  `position` json DEFAULT NULL COMMENT '前端画布位置',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_version_node` (`workflow_id`, `version_id`, `node_key`, `tenant_id`),
  KEY `idx_workflow_version` (`workflow_id`, `version_id`),
  KEY `idx_node_type` (`node_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AIGC 工作流节点定义表';

CREATE TABLE IF NOT EXISTS `aigc_workflow_edge` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `workflow_id` bigint NOT NULL COMMENT '工作流 ID',
  `version_id` bigint DEFAULT NULL COMMENT '版本 ID',
  `edge_key` varchar(128) NOT NULL COMMENT '边唯一键',
  `source_node_key` varchar(128) NOT NULL COMMENT '上游节点',
  `target_node_key` varchar(128) NOT NULL COMMENT '下游节点',
  `condition_config` json DEFAULT NULL COMMENT '条件配置',
  `input_mapping` json DEFAULT NULL COMMENT '入参映射',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_version_edge` (`workflow_id`, `version_id`, `edge_key`, `tenant_id`),
  KEY `idx_workflow_version` (`workflow_id`, `version_id`),
  KEY `idx_source_target` (`source_node_key`, `target_node_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AIGC 工作流边关系表';

CREATE TABLE IF NOT EXISTS `aigc_workflow_version` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `workflow_id` bigint NOT NULL COMMENT '工作流 ID',
  `version_no` int NOT NULL COMMENT '版本号',
  `version_name` varchar(128) DEFAULT NULL COMMENT '版本名称',
  `definition_snapshot` json DEFAULT NULL COMMENT '定义快照',
  `node_snapshot` json DEFAULT NULL COMMENT '节点快照',
  `edge_snapshot` json DEFAULT NULL COMMENT '边快照',
  `status` varchar(32) NOT NULL COMMENT '状态',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_workflow_version` (`workflow_id`, `version_no`, `tenant_id`),
  KEY `idx_workflow_status` (`workflow_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AIGC 工作流版本表';

CREATE TABLE IF NOT EXISTS `aigc_workflow_instance` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `instance_no` varchar(64) NOT NULL COMMENT '实例编号',
  `workflow_id` bigint NOT NULL COMMENT '工作流 ID',
  `workflow_version_id` bigint DEFAULT NULL COMMENT '工作流版本 ID',
  `template_id` bigint DEFAULT NULL COMMENT '来源模板',
  `user_id` bigint NOT NULL COMMENT '用户 ID',
  `status` varchar(32) NOT NULL COMMENT '状态',
  `input_data` json DEFAULT NULL COMMENT '输入数据',
  `output_data` json DEFAULT NULL COMMENT '输出数据',
  `main_task_id` bigint DEFAULT NULL COMMENT '主任务 ID',
  `freeze_id` bigint DEFAULT NULL COMMENT '计费冻结 ID',
  `estimate_amount` bigint DEFAULT NULL COMMENT '预估费用',
  `actual_amount` bigint DEFAULT NULL COMMENT '实际费用',
  `progress` int NOT NULL DEFAULT 0 COMMENT '进度',
  `fail_reason` varchar(512) DEFAULT NULL COMMENT '失败原因',
  `fail_message` varchar(2048) DEFAULT NULL COMMENT '失败详情',
  `start_time` datetime DEFAULT NULL COMMENT '开始时间',
  `finish_time` datetime DEFAULT NULL COMMENT '结束时间',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_instance_no` (`tenant_id`, `instance_no`),
  KEY `idx_user_status` (`tenant_id`, `user_id`, `status`),
  KEY `idx_workflow_status` (`workflow_id`, `status`),
  KEY `idx_main_task` (`main_task_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AIGC 工作流实例表';

CREATE TABLE IF NOT EXISTS `aigc_workflow_node_instance` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `workflow_instance_id` bigint NOT NULL COMMENT '工作流实例',
  `node_id` bigint DEFAULT NULL COMMENT '节点定义',
  `node_key` varchar(128) NOT NULL COMMENT '节点键',
  `node_type` varchar(64) NOT NULL COMMENT '节点类型',
  `status` varchar(32) NOT NULL COMMENT '状态',
  `task_id` bigint DEFAULT NULL COMMENT '关联任务 ID',
  `gen_record_id` bigint DEFAULT NULL COMMENT '生成记录 ID',
  `input_data` json DEFAULT NULL COMMENT '节点入参',
  `output_data` json DEFAULT NULL COMMENT '节点出参',
  `asset_ids` json DEFAULT NULL COMMENT '输出资产',
  `retry_count` int NOT NULL DEFAULT 0 COMMENT '重试次数',
  `max_retry_count` int NOT NULL DEFAULT 0 COMMENT '最大重试次数',
  `cost_amount` bigint DEFAULT NULL COMMENT '节点费用',
  `start_time` datetime DEFAULT NULL COMMENT '开始时间',
  `finish_time` datetime DEFAULT NULL COMMENT '结束时间',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_instance_node` (`workflow_instance_id`, `node_key`, `tenant_id`),
  KEY `idx_instance_status` (`workflow_instance_id`, `status`),
  KEY `idx_task_id` (`task_id`),
  KEY `idx_gen_record_id` (`gen_record_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AIGC 工作流节点实例表';

CREATE TABLE IF NOT EXISTS `aigc_workflow_log` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `workflow_instance_id` bigint NOT NULL COMMENT '工作流实例',
  `node_instance_id` bigint DEFAULT NULL COMMENT '节点实例',
  `log_type` varchar(64) NOT NULL COMMENT '日志类型',
  `from_status` varchar(32) DEFAULT NULL COMMENT '原状态',
  `to_status` varchar(32) DEFAULT NULL COMMENT '目标状态',
  `summary` varchar(512) DEFAULT NULL COMMENT '摘要',
  `detail_data` json DEFAULT NULL COMMENT '详情 JSON',
  `cost_millis` bigint DEFAULT NULL COMMENT '耗时毫秒',
  `user_id` bigint DEFAULT NULL COMMENT '用户 ID',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  KEY `idx_instance_node` (`workflow_instance_id`, `node_instance_id`),
  KEY `idx_user_time` (`user_id`, `create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AIGC 工作流日志表';

CREATE TABLE IF NOT EXISTS `aigc_canvas_project` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `owner_user_id` bigint NOT NULL COMMENT '拥有者用户 ID',
  `name` varchar(128) NOT NULL COMMENT '项目名称',
  `kind` varchar(32) NOT NULL DEFAULT 'image' COMMENT '项目类型',
  `cover_asset_id` bigint DEFAULT NULL COMMENT '封面资产 ID',
  `current_version` bigint NOT NULL DEFAULT 0 COMMENT '当前画布版本',
  `latest_snapshot_id` bigint DEFAULT NULL COMMENT '最新快照 ID',
  `status` varchar(32) NOT NULL DEFAULT 'NORMAL' COMMENT '项目状态',
  `node_count` int NOT NULL DEFAULT 0 COMMENT '节点数',
  `asset_count` int NOT NULL DEFAULT 0 COMMENT '资产数',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  KEY `idx_owner_update_time` (`tenant_id`, `owner_user_id`, `update_time`),
  KEY `idx_status` (`tenant_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AIGC 画布项目表';

CREATE TABLE IF NOT EXISTS `aigc_canvas_member` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `project_id` bigint NOT NULL COMMENT '项目 ID',
  `user_id` bigint NOT NULL COMMENT '用户 ID',
  `role` varchar(32) NOT NULL COMMENT '角色 owner/editor/viewer',
  `invite_user_id` bigint DEFAULT NULL COMMENT '邀请人',
  `joined_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '加入时间',
  `last_active_time` datetime DEFAULT NULL COMMENT '最后活跃时间',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_project_user` (`tenant_id`, `project_id`, `user_id`),
  KEY `idx_user` (`tenant_id`, `user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AIGC 画布成员表';

CREATE TABLE IF NOT EXISTS `aigc_canvas_snapshot` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `project_id` bigint NOT NULL COMMENT '项目 ID',
  `version` bigint NOT NULL COMMENT '快照版本',
  `nodes_json` json NOT NULL COMMENT '节点 JSON',
  `edges_json` json NOT NULL COMMENT '连线 JSON',
  `viewport_json` json DEFAULT NULL COMMENT '视口 JSON',
  `created_by` bigint DEFAULT NULL COMMENT '创建用户',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_project_version` (`tenant_id`, `project_id`, `version`),
  KEY `idx_project_time` (`tenant_id`, `project_id`, `create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AIGC 画布快照表';

CREATE TABLE IF NOT EXISTS `aigc_canvas_sketch` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `project_id` bigint NOT NULL COMMENT '项目 ID',
  `node_id` varchar(128) NOT NULL COMMENT '节点 ID',
  `scene_json` json NOT NULL COMMENT 'tldraw 场景 JSON',
  `preview_url` varchar(1024) DEFAULT NULL COMMENT '预览图地址',
  `preview_data_url` mediumtext COMMENT '预览图 data URL',
  `preview_asset_id` bigint DEFAULT NULL COMMENT '预览资产 ID',
  `preview_asset_version_id` bigint DEFAULT NULL COMMENT '预览资产版本 ID',
  `mime_type` varchar(64) NOT NULL DEFAULT 'image/png' COMMENT '导出图片类型',
  `width` int DEFAULT NULL COMMENT '导出宽度',
  `height` int DEFAULT NULL COMMENT '导出高度',
  `background` varchar(32) NOT NULL DEFAULT 'white' COMMENT '导出背景 white/transparent',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_project_node` (`tenant_id`, `project_id`, `node_id`),
  KEY `idx_project_update_time` (`tenant_id`, `project_id`, `update_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AIGC 画布草图表';

CREATE TABLE IF NOT EXISTS `aigc_canvas_operation_log` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `project_id` bigint NOT NULL COMMENT '项目 ID',
  `client_id` varchar(128) NOT NULL COMMENT '客户端实例 ID',
  `op_id` varchar(128) NOT NULL COMMENT '客户端操作 ID',
  `actor_user_id` bigint NOT NULL COMMENT '操作用户 ID',
  `base_version` bigint NOT NULL COMMENT '客户端基于版本',
  `next_version` bigint NOT NULL COMMENT '服务端应用后版本',
  `operation_type` varchar(64) NOT NULL COMMENT '操作类型',
  `operation_json` json NOT NULL COMMENT '操作 JSON',
  `inverse_operation_json` json DEFAULT NULL COMMENT '反向操作 JSON',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_project_client_op` (`tenant_id`, `project_id`, `client_id`, `op_id`),
  UNIQUE KEY `uk_project_next_version` (`tenant_id`, `project_id`, `next_version`),
  KEY `idx_project_version` (`tenant_id`, `project_id`, `next_version`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AIGC 画布操作日志表';

CREATE TABLE IF NOT EXISTS `aigc_canvas_asset_ref` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `project_id` bigint NOT NULL COMMENT '项目 ID',
  `node_id` varchar(128) NOT NULL COMMENT '节点 ID',
  `asset_id` bigint NOT NULL COMMENT '资产 ID',
  `usage_type` varchar(64) NOT NULL COMMENT '用途 source/input/output/cover/reference',
  `source_task_id` bigint DEFAULT NULL COMMENT '来源任务 ID',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_project_node_asset_usage` (`tenant_id`, `project_id`, `node_id`, `asset_id`, `usage_type`),
  KEY `idx_project_node` (`tenant_id`, `project_id`, `node_id`),
  KEY `idx_asset` (`tenant_id`, `asset_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AIGC 画布资产引用表';
