
--- #################### 网关关相关配置 ####################
spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: system-admin-api
              uri: grayLb://system-server
              predicates:
                - Path=/admin-api/system/**
              filters:
                - RewritePath=/admin-api/system/v3/api-docs, /v3/api-docs

            - id: system-app-api
              uri: grayLb://system-server
              predicates:
                - Path=/app-api/system/**
              filters:
                - RewritePath=/app-api/system/v3/api-docs, /v3/api-docs
            - id: infra-admin-api
              uri: grayLb://infra-server
              predicates:
                - Path=/admin-api/infra/**
              filters:
                - RewritePath=/admin-api/infra/v3/api-docs, /v3/api-docs
            - id: infra-app-api
              uri: grayLb://infra-server
              predicates:
                - Path=/app-api/infra/**
              filters:
                - RewritePath=/app-api/infra/v3/api-docs, /v3/api-docs
            - id: member-admin-api
              uri: grayLb://member-server
              predicates:
                - Path=/admin-api/member/**
              filters:
                - RewritePath=/admin-api/member/v3/api-docs, /v3/api-docs
            - id: member-app-api
              uri: grayLb://member-server
              predicates:
                - Path=/app-api/member/**
              filters:
                - RewritePath=/app-api/member/v3/api-docs, /v3/api-docs

--- #################### Knife4j 相关配置 ####################
knife4j:
  gateway:
    enabled: true
    routes:
      - name: system-server
        service-name: system-server
        url: /admin-api/system/v3/api-docs
      - name: system-app-server
        service-name: system-app-server
        url: /app-api/system/v3/api-docs
      - name: infra-server
        service-name: infra-server
        url: /admin-api/infra/v3/api-docs
      - name: infra-app-server
        service-name: infra-app-server
        url: /app-api/infra/v3/api-docs
      - name: member-server
        service-name: member-server
        url: /admin-api/member/v3/api-docs
      - name: member-app-server
        service-name: member-app-server
        url: /app-api/member/v3/api-docs
--- #################### 日志相关配置 ####################
logging:
  level:
    cn.iocoder.yudao.gateway: debug
    org.springframework.cloud.gateway: info