CREATE TABLE IF NOT EXISTS `aigc_gen_record` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `task_id` bigint DEFAULT NULL COMMENT 'AIGC 统一任务编号',
  `user_id` bigint NOT NULL COMMENT '用户编号',
  `generate_no` varchar(64) NOT NULL COMMENT '生成流水号',
  `client_request_id` varchar(128) DEFAULT NULL COMMENT '客户端请求编号',
  `generate_type` varchar(32) NOT NULL COMMENT '生成类型',
  `generate_mode` varchar(32) NOT NULL COMMENT '生成模式',
  `model_id` bigint NOT NULL COMMENT '模型编号',
  `model_code` varchar(64) DEFAULT NULL COMMENT '模型编码快照',
  `channel_id` bigint DEFAULT NULL COMMENT '渠道实现编号',
  `provider_model` varchar(128) DEFAULT NULL COMMENT '渠道上游模型标识快照',
  `provider_id` bigint DEFAULT NULL COMMENT '渠道商编号',
  `provider_code` varchar(64) DEFAULT NULL COMMENT '渠道编码快照',
  `provider_task_id` varchar(128) DEFAULT NULL COMMENT '第三方任务编号',
  `provider_status` varchar(64) DEFAULT NULL COMMENT '第三方任务状态',
  `status` varchar(32) NOT NULL COMMENT '生成状态',
  `prompt` text DEFAULT NULL COMMENT '提示词',
  `input_params` json DEFAULT NULL COMMENT '输入参数快照',
  `output_text` text DEFAULT NULL COMMENT '文本输出',
  `output_data` json DEFAULT NULL COMMENT '结构化输出',
  `output_urls` json DEFAULT NULL COMMENT '第三方结果 URL',
  `asset_ids` json DEFAULT NULL COMMENT '资产编号列表',
  `freeze_id` bigint DEFAULT NULL COMMENT '冻结记录编号',
  `price_amount` decimal(18, 6) DEFAULT NULL COMMENT '销售价快照',
  `cost_amount` decimal(18, 6) DEFAULT NULL COMMENT '成本价快照',
  `submit_time` datetime DEFAULT NULL COMMENT '提交第三方时间',
  `callback_time` datetime DEFAULT NULL COMMENT '回调时间',
  `finish_time` datetime DEFAULT NULL COMMENT '完成时间',
  `fail_reason` varchar(64) DEFAULT NULL COMMENT '失败原因类型',
  `fail_message` varchar(512) DEFAULT NULL COMMENT '失败信息',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_generate_no` (`tenant_id`, `generate_no`),
  UNIQUE KEY `uk_tenant_task` (`tenant_id`, `task_id`),
  KEY `idx_tenant_user_type_time` (`tenant_id`, `user_id`, `generate_type`, `create_time`),
  KEY `idx_tenant_status_time` (`tenant_id`, `status`, `create_time`),
  KEY `idx_tenant_provider_task` (`tenant_id`, `provider_code`, `provider_task_id`),
  UNIQUE KEY `uk_tenant_client_request` (`tenant_id`, `user_id`, `client_request_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AIGC 生成记录表';

CREATE TABLE IF NOT EXISTS `aigc_gen_attempt` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `record_id` bigint NOT NULL COMMENT '生成记录编号',
  `task_id` bigint DEFAULT NULL COMMENT 'AIGC 统一任务编号',
  `attempt_no` int NOT NULL COMMENT '尝试序号',
  `batch_no` int NOT NULL DEFAULT 1 COMMENT '批次序号',
  `strategy` varchar(32) NOT NULL COMMENT '尝试策略',
  `model_id` bigint NOT NULL COMMENT '模型编号',
  `model_code` varchar(64) DEFAULT NULL COMMENT '模型编码快照',
  `channel_id` bigint DEFAULT NULL COMMENT '渠道实现编号',
  `provider_model` varchar(128) DEFAULT NULL COMMENT '供应商模型标识',
  `provider_id` bigint DEFAULT NULL COMMENT '供应商编号',
  `provider_code` varchar(64) DEFAULT NULL COMMENT '供应商编码',
  `provider_task_id` varchar(128) DEFAULT NULL COMMENT '第三方任务编号',
  `provider_status` varchar(64) DEFAULT NULL COMMENT '第三方任务状态',
  `status` varchar(32) NOT NULL COMMENT '尝试状态',
  `sale_amount` decimal(18, 6) DEFAULT NULL COMMENT '销售金额快照',
  `cost_amount` decimal(18, 6) DEFAULT NULL COMMENT '成本金额快照',
  `currency_type` varchar(32) DEFAULT NULL COMMENT '币种',
  `billing_unit` varchar(32) DEFAULT NULL COMMENT '计费单位',
  `price_snapshot` json DEFAULT NULL COMMENT '价格快照',
  `request_summary` json DEFAULT NULL COMMENT '请求摘要',
  `response_summary` json DEFAULT NULL COMMENT '响应摘要',
  `fail_code` varchar(64) DEFAULT NULL COMMENT '失败编码',
  `fail_reason` varchar(512) DEFAULT NULL COMMENT '失败原因',
  `winner` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否最终成功尝试',
  `submit_time` datetime DEFAULT NULL COMMENT '提交时间',
  `callback_time` datetime DEFAULT NULL COMMENT '回调时间',
  `finish_time` datetime DEFAULT NULL COMMENT '完成时间',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_record_attempt` (`tenant_id`, `record_id`, `attempt_no`),
  KEY `idx_tenant_record_status` (`tenant_id`, `record_id`, `status`),
  KEY `idx_tenant_provider_task` (`tenant_id`, `provider_code`, `provider_task_id`),
  KEY `idx_tenant_task` (`tenant_id`, `task_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AIGC 生成尝试表';

CREATE TABLE IF NOT EXISTS `aigc_gen_callback` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `record_id` bigint DEFAULT NULL COMMENT '生成记录编号',
  `task_id` bigint DEFAULT NULL COMMENT 'AIGC 统一任务编号',
  `provider_code` varchar(64) NOT NULL COMMENT '渠道编码',
  `provider_task_id` varchar(128) NOT NULL COMMENT '第三方任务编号',
  `callback_type` varchar(32) DEFAULT NULL COMMENT '回调类型',
  `callback_no` varchar(128) DEFAULT NULL COMMENT '回调唯一编号',
  `signature_valid` bit(1) NOT NULL DEFAULT b'0' COMMENT '签名是否通过',
  `raw_body` text DEFAULT NULL COMMENT '回调原文',
  `parsed_data` json DEFAULT NULL COMMENT '解析数据',
  `process_status` varchar(32) NOT NULL COMMENT '处理状态',
  `process_message` varchar(512) DEFAULT NULL COMMENT '处理说明',
  `process_time` datetime DEFAULT NULL COMMENT '处理时间',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  `attempt_id` bigint DEFAULT NULL COMMENT '生成尝试编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_provider_callback` (`tenant_id`, `provider_code`, `callback_no`),
  KEY `idx_tenant_provider_task` (`tenant_id`, `provider_code`, `provider_task_id`),
  KEY `idx_tenant_task` (`tenant_id`, `task_id`),
  KEY `idx_tenant_attempt` (`tenant_id`, `attempt_id`),
  KEY `idx_tenant_status_time` (`tenant_id`, `process_status`, `create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AIGC 生成回调表';

CREATE TABLE IF NOT EXISTS `aigc_gen_provider_log` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `record_id` bigint DEFAULT NULL COMMENT '生成记录编号',
  `task_id` bigint DEFAULT NULL COMMENT 'AIGC 统一任务编号',
  `provider_code` varchar(64) NOT NULL COMMENT '渠道编码',
  `model_code` varchar(64) DEFAULT NULL COMMENT '模型编码',
  `api_action` varchar(32) NOT NULL COMMENT '调用动作',
  `request_id` varchar(128) DEFAULT NULL COMMENT '请求编号',
  `request_summary` json DEFAULT NULL COMMENT '请求摘要',
  `response_summary` json DEFAULT NULL COMMENT '响应摘要',
  `success` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否成功',
  `http_status` int DEFAULT NULL COMMENT 'HTTP 状态码',
  `error_code` varchar(64) DEFAULT NULL COMMENT '错误码',
  `error_message` varchar(512) DEFAULT NULL COMMENT '错误信息',
  `duration_ms` bigint DEFAULT NULL COMMENT '调用耗时毫秒',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  `attempt_id` bigint DEFAULT NULL COMMENT '生成尝试编号',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_record` (`tenant_id`, `record_id`),
  KEY `idx_tenant_attempt` (`tenant_id`, `attempt_id`),
  KEY `idx_tenant_provider_time` (`tenant_id`, `provider_code`, `create_time`),
  KEY `idx_tenant_success_time` (`tenant_id`, `success`, `create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AIGC 渠道调用日志表';
