--- #################### 注册中心 + 配置中心相关配置 ####################

spring:
  cloud:
    nacos:
      server-addr: ${NACOS_SERVER_ADDR:10.66.0.2:8848}
      username: ${NACOS_USERNAME:nacos}
      password: ${NACOS_PASSWORD:nacos}
      discovery:
        namespace: prod
        group: DEFAULT_GROUP
        metadata:
          version: 1.0.0
      config:
        namespace: prod
        group: DEFAULT_GROUP

--- #################### 数据库相关配置 ####################

spring:
  datasource:
    druid:
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: false
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 500
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
    dynamic:
      druid:
        initial-size: 5
        min-idle: 10
        max-active: 50
        max-wait: 60000
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 600000
        max-evictable-idle-time-millis: 1800000
        validation-query: SELECT 1 FROM DUAL
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
      primary: master
      datasource:
        master:
          url: ${SYSTEM_DB_MASTER_URL:jdbc:mysql://mysql:3306/system_db?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true&rewriteBatchedStatements=true}
          username: ${SYSTEM_DB_USERNAME:root}
          password: ${SYSTEM_DB_PASSWORD:123456}
        slave:
          lazy: true
          url: ${SYSTEM_DB_SLAVE_URL:${SYSTEM_DB_MASTER_URL:jdbc:mysql://mysql:3306/system_db?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true&rewriteBatchedStatements=true}}
          username: ${SYSTEM_DB_SLAVE_USERNAME:${SYSTEM_DB_USERNAME:root}}
          password: ${SYSTEM_DB_SLAVE_PASSWORD:${SYSTEM_DB_PASSWORD:123456}}

  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      database: ${SYSTEM_REDIS_DATABASE:1}

--- #################### MQ 消息队列相关配置 ####################

rocketmq:
  name-server: ${ROCKETMQ_NAME_SERVER:rocketmq:9876}

spring:
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

--- #################### 定时任务相关配置 ####################

xxl:
  job:
    enabled: true
    admin:
      addresses: ${XXL_JOB_ADMIN_ADDRESSES:http://10.66.0.2:9090/xxl-job-admin}

--- #################### 服务保障相关配置 ####################

lock4j:
  acquire-timeout: 3000
  expire: 30000
