CREATE TABLE IF NOT EXISTS aigc_wallet (
    id bigint NOT NULL AUTO_INCREMENT COMMENT '钱包编号',
    user_id bigint NOT NULL COMMENT '用户编号',
    balance decimal(18,6) NOT NULL DEFAULT 0.000000 COMMENT '可用积分余额',
    frozen_balance decimal(18,6) NOT NULL DEFAULT 0.000000 COMMENT '冻结积分余额',
    total_recharge decimal(18,6) NOT NULL DEFAULT 0.000000 COMMENT '累计充值积分',
    total_gift decimal(18,6) NOT NULL DEFAULT 0.000000 COMMENT '累计赠送积分',
    total_consume decimal(18,6) NOT NULL DEFAULT 0.000000 COMMENT '累计消费积分',
    total_refund decimal(18,6) NOT NULL DEFAULT 0.000000 COMMENT '累计退款积分',
    status tinyint NOT NULL DEFAULT 0 COMMENT '钱包状态',
    last_trans_time datetime NULL COMMENT '最后交易时间',
    remark varchar(512) NULL COMMENT '备注',
    creator varchar(64) NULL DEFAULT '' COMMENT '创建者',
    create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updater varchar(64) NULL DEFAULT '' COMMENT '更新者',
    update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted bit NOT NULL DEFAULT b'0' COMMENT '是否删除',
    tenant_id bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_user_tenant (user_id, tenant_id),
    KEY idx_status (status),
    KEY idx_last_trans_time (last_trans_time)
) COMMENT='AIGC 用户积分钱包';

CREATE TABLE IF NOT EXISTS aigc_quota_freeze (
    id bigint NOT NULL AUTO_INCREMENT COMMENT '冻结记录编号',
    freeze_no varchar(64) NOT NULL COMMENT '冻结单号',
    wallet_id bigint NOT NULL COMMENT '钱包编号',
    user_id bigint NOT NULL COMMENT '用户编号',
    biz_type varchar(64) NOT NULL COMMENT '业务类型',
    biz_id varchar(128) NOT NULL COMMENT '业务编号',
    task_id bigint NULL COMMENT '任务编号',
    task_no varchar(64) NULL COMMENT '任务单号',
    amount decimal(18,6) NOT NULL COMMENT '冻结积分数量',
    confirmed_amount decimal(18,6) NOT NULL DEFAULT 0.000000 COMMENT '已确认扣减积分数量',
    released_amount decimal(18,6) NOT NULL DEFAULT 0.000000 COMMENT '已释放积分数量',
    status varchar(32) NOT NULL COMMENT '冻结状态',
    expire_time datetime NULL COMMENT '过期时间',
    confirm_time datetime NULL COMMENT '确认扣减时间',
    release_time datetime NULL COMMENT '释放时间',
    reason varchar(512) NULL COMMENT '冻结原因',
    creator varchar(64) NULL DEFAULT '' COMMENT '创建者',
    create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updater varchar(64) NULL DEFAULT '' COMMENT '更新者',
    update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted bit NOT NULL DEFAULT b'0' COMMENT '是否删除',
    tenant_id bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_freeze_no (freeze_no),
    UNIQUE KEY uk_biz (biz_type, biz_id, tenant_id),
    KEY idx_user_status (user_id, status),
    KEY idx_task_id (task_id),
    KEY idx_expire_status (expire_time, status)
) COMMENT='AIGC 积分冻结记录';

CREATE TABLE IF NOT EXISTS aigc_billing_record (
    id bigint NOT NULL AUTO_INCREMENT COMMENT '流水编号',
    record_no varchar(64) NOT NULL COMMENT '流水单号',
    wallet_id bigint NOT NULL COMMENT '钱包编号',
    user_id bigint NOT NULL COMMENT '用户编号',
    biz_type varchar(64) NOT NULL COMMENT '业务类型',
    biz_id varchar(128) NOT NULL COMMENT '业务编号',
    record_type varchar(64) NOT NULL COMMENT '流水类型',
    title varchar(128) NULL COMMENT '流水标题',
    amount decimal(18,6) NOT NULL COMMENT '变动积分数量',
    balance_after decimal(18,6) NOT NULL COMMENT '变动后可用余额',
    frozen_balance_after decimal(18,6) NOT NULL COMMENT '变动后冻结余额',
    freeze_id bigint NULL COMMENT '冻结记录编号',
    task_id bigint NULL COMMENT '任务编号',
    model_id bigint NULL COMMENT '模型编号',
    provider_id bigint NULL COMMENT '服务商编号',
    currency_type varchar(32) NOT NULL DEFAULT 'POINT' COMMENT '币种类型',
    price_snapshot json NULL COMMENT '价格快照',
    extra_info json NULL COMMENT '扩展信息',
    creator varchar(64) NULL DEFAULT '' COMMENT '创建者',
    create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updater varchar(64) NULL DEFAULT '' COMMENT '更新者',
    update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted bit NOT NULL DEFAULT b'0' COMMENT '是否删除',
    tenant_id bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_record_no (record_no),
    UNIQUE KEY uk_biz_tenant (biz_type, biz_id, tenant_id),
    KEY idx_wallet_time (wallet_id, create_time),
    KEY idx_user_time (user_id, create_time),
    KEY idx_task_id (task_id),
    KEY idx_record_type (record_type)
) COMMENT='AIGC 计费流水';

CREATE TABLE IF NOT EXISTS aigc_cost_record (
    id bigint NOT NULL AUTO_INCREMENT COMMENT '成本记录编号',
    cost_no varchar(64) NOT NULL COMMENT '成本单号',
    task_id bigint NOT NULL COMMENT '任务编号',
    task_no varchar(64) NULL COMMENT '任务单号',
    user_id bigint NOT NULL COMMENT '用户编号',
    model_id bigint NULL COMMENT '模型编号',
    provider_id bigint NULL COMMENT '服务商编号',
    capability varchar(64) NULL COMMENT '模型能力',
    billing_unit varchar(32) NULL COMMENT '计费单位',
    usage_amount decimal(18,6) NULL COMMENT '用量数量',
    cost_amount decimal(18,6) NOT NULL COMMENT '成本金额',
    sale_amount decimal(18,6) NOT NULL COMMENT '销售金额',
    gross_profit decimal(18,6) NOT NULL COMMENT '毛利金额',
    gross_profit_rate decimal(18,6) NOT NULL COMMENT '毛利率',
    currency_type varchar(32) NOT NULL DEFAULT 'POINT' COMMENT '币种类型',
    usage_snapshot json NULL COMMENT '用量快照',
    price_snapshot json NULL COMMENT '价格快照',
    status varchar(32) NOT NULL COMMENT '记录状态',
    creator varchar(64) NULL DEFAULT '' COMMENT '创建者',
    create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updater varchar(64) NULL DEFAULT '' COMMENT '更新者',
    update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted bit NOT NULL DEFAULT b'0' COMMENT '是否删除',
    tenant_id bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
    record_id bigint NULL COMMENT '生成记录编号',
    attempt_id bigint NULL COMMENT '生成尝试编号',
    channel_id bigint NULL COMMENT '渠道编号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_cost_no (cost_no),
    UNIQUE KEY uk_attempt_id (attempt_id),
    KEY idx_task_id (task_id),
    KEY idx_record_id (record_id),
    KEY idx_model_time (model_id, create_time),
    KEY idx_provider_time (provider_id, create_time),
    KEY idx_user_time (user_id, create_time),
    KEY idx_status (status)
) COMMENT='AIGC 成本记录';

CREATE TABLE IF NOT EXISTS aigc_recharge_order (
    id bigint NOT NULL AUTO_INCREMENT COMMENT '充值订单编号',
    recharge_no varchar(64) NOT NULL COMMENT '充值订单号',
    wallet_id bigint NOT NULL COMMENT '钱包编号',
    user_id bigint NOT NULL COMMENT '用户编号',
    recharge_type varchar(32) NOT NULL COMMENT '充值类型',
    package_id bigint NULL COMMENT '充值套餐编号',
    pay_amount int NOT NULL DEFAULT 0 COMMENT '支付金额，单位：分',
    point_amount decimal(18,6) NOT NULL DEFAULT 0.000000 COMMENT '充值积分数量',
    gift_amount decimal(18,6) NOT NULL DEFAULT 0.000000 COMMENT '赠送积分数量',
    total_point_amount decimal(18,6) NOT NULL DEFAULT 0.000000 COMMENT '到账积分总数',
    pay_order_id bigint NULL COMMENT '支付订单编号',
    pay_order_no varchar(64) NULL COMMENT '支付订单号',
    pay_channel_code varchar(32) NULL COMMENT '支付渠道编码',
    status varchar(32) NOT NULL COMMENT '订单状态',
    pay_time datetime NULL COMMENT '支付时间',
    close_time datetime NULL COMMENT '关闭时间',
    refund_time datetime NULL COMMENT '退款时间',
    operator_id bigint NULL COMMENT '操作人编号',
    remark varchar(512) NULL COMMENT '备注',
    creator varchar(64) NULL DEFAULT '' COMMENT '创建者',
    create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updater varchar(64) NULL DEFAULT '' COMMENT '更新者',
    update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted bit NOT NULL DEFAULT b'0' COMMENT '是否删除',
    tenant_id bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_recharge_no (recharge_no),
    UNIQUE KEY uk_pay_order_id (pay_order_id),
    KEY idx_wallet_time (wallet_id, create_time),
    KEY idx_user_package_status_time (user_id, package_id, status, create_time),
    KEY idx_user_status (user_id, status),
    KEY idx_status_create_time (status, create_time)
) COMMENT='AIGC 充值订单';

CREATE TABLE IF NOT EXISTS aigc_recharge_package (
    id bigint NOT NULL AUTO_INCREMENT COMMENT '充值套餐编号',
    name varchar(64) NOT NULL COMMENT '套餐名称',
    pay_amount int NOT NULL DEFAULT 0 COMMENT '支付金额，单位：分',
    point_amount decimal(18,6) NOT NULL DEFAULT 0.000000 COMMENT '充值积分数量',
    gift_amount decimal(18,6) NOT NULL DEFAULT 0.000000 COMMENT '赠送积分数量',
    total_point_amount decimal(18,6) NOT NULL DEFAULT 0.000000 COMMENT '到账积分总数',
    description varchar(255) NULL COMMENT '描述',
    features varchar(1000) NULL COMMENT '权益说明，每行一条',
    recommend_status bit NOT NULL DEFAULT b'0' COMMENT '是否推荐',
    sort int NOT NULL DEFAULT 0 COMMENT '排序',
    status tinyint NOT NULL DEFAULT 0 COMMENT '状态',
    remark varchar(512) NULL COMMENT '备注',
    creator varchar(64) NULL DEFAULT '' COMMENT '创建者',
    create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updater varchar(64) NULL DEFAULT '' COMMENT '更新者',
    update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted bit NOT NULL DEFAULT b'0' COMMENT '是否删除',
    tenant_id bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
    PRIMARY KEY (id),
    KEY idx_status_sort (status, sort)
) COMMENT='AIGC 充值套餐';
