CREATE TABLE IF NOT EXISTS aigc_wallet (
    id bigint NOT NULL AUTO_INCREMENT,
    user_id bigint NOT NULL,
    balance decimal(18,6) NOT NULL DEFAULT 0.000000,
    frozen_balance decimal(18,6) NOT NULL DEFAULT 0.000000,
    total_recharge decimal(18,6) NOT NULL DEFAULT 0.000000,
    total_gift decimal(18,6) NOT NULL DEFAULT 0.000000,
    total_consume decimal(18,6) NOT NULL DEFAULT 0.000000,
    total_refund decimal(18,6) NOT NULL DEFAULT 0.000000,
    status tinyint NOT NULL DEFAULT 0,
    last_trans_time datetime NULL,
    remark varchar(512) NULL,
    creator varchar(64) NULL DEFAULT '',
    create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updater varchar(64) NULL DEFAULT '',
    update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted bit NOT NULL DEFAULT b'0',
    tenant_id bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_user_tenant (user_id, tenant_id),
    KEY idx_status (status),
    KEY idx_last_trans_time (last_trans_time)
) COMMENT='AIGC 用户积分钱包';

CREATE TABLE IF NOT EXISTS aigc_quota_freeze (
    id bigint NOT NULL AUTO_INCREMENT,
    freeze_no varchar(64) NOT NULL,
    wallet_id bigint NOT NULL,
    user_id bigint NOT NULL,
    biz_type varchar(64) NOT NULL,
    biz_id varchar(128) NOT NULL,
    task_id bigint NULL,
    task_no varchar(64) NULL,
    amount decimal(18,6) NOT NULL,
    confirmed_amount decimal(18,6) NOT NULL DEFAULT 0.000000,
    released_amount decimal(18,6) NOT NULL DEFAULT 0.000000,
    status varchar(32) NOT NULL,
    expire_time datetime NULL,
    confirm_time datetime NULL,
    release_time datetime NULL,
    reason varchar(512) NULL,
    creator varchar(64) NULL DEFAULT '',
    create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updater varchar(64) NULL DEFAULT '',
    update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted bit NOT NULL DEFAULT b'0',
    tenant_id bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_freeze_no (freeze_no),
    UNIQUE KEY uk_biz (biz_type, biz_id, tenant_id),
    KEY idx_user_status (user_id, status),
    KEY idx_task_id (task_id),
    KEY idx_expire_status (expire_time, status)
) COMMENT='AIGC 积分冻结记录';

CREATE TABLE IF NOT EXISTS aigc_billing_record (
    id bigint NOT NULL AUTO_INCREMENT,
    record_no varchar(64) NOT NULL,
    wallet_id bigint NOT NULL,
    user_id bigint NOT NULL,
    biz_type varchar(64) NOT NULL,
    biz_id varchar(128) NOT NULL,
    record_type varchar(64) NOT NULL,
    title varchar(128) NULL,
    amount decimal(18,6) NOT NULL,
    balance_after decimal(18,6) NOT NULL,
    frozen_balance_after decimal(18,6) NOT NULL,
    freeze_id bigint NULL,
    task_id bigint NULL,
    model_id bigint NULL,
    provider_id bigint NULL,
    currency_type varchar(32) NOT NULL DEFAULT 'POINT',
    price_snapshot json NULL,
    extra_info json NULL,
    creator varchar(64) NULL DEFAULT '',
    create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updater varchar(64) NULL DEFAULT '',
    update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted bit NOT NULL DEFAULT b'0',
    tenant_id bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_record_no (record_no),
    KEY idx_wallet_time (wallet_id, create_time),
    KEY idx_user_time (user_id, create_time),
    KEY idx_biz (biz_type, biz_id),
    KEY idx_task_id (task_id),
    KEY idx_record_type (record_type)
) COMMENT='AIGC 计费流水';

CREATE TABLE IF NOT EXISTS aigc_cost_record (
    id bigint NOT NULL AUTO_INCREMENT,
    cost_no varchar(64) NOT NULL,
    task_id bigint NOT NULL,
    task_no varchar(64) NULL,
    user_id bigint NOT NULL,
    model_id bigint NULL,
    provider_id bigint NULL,
    capability varchar(64) NULL,
    billing_unit varchar(32) NULL,
    usage_amount decimal(18,6) NULL,
    cost_amount decimal(18,6) NOT NULL,
    sale_amount decimal(18,6) NOT NULL,
    gross_profit decimal(18,6) NOT NULL,
    gross_profit_rate decimal(18,6) NOT NULL,
    currency_type varchar(32) NOT NULL DEFAULT 'POINT',
    usage_snapshot json NULL,
    price_snapshot json NULL,
    status varchar(32) NOT NULL,
    creator varchar(64) NULL DEFAULT '',
    create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updater varchar(64) NULL DEFAULT '',
    update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted bit NOT NULL DEFAULT b'0',
    tenant_id bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_cost_no (cost_no),
    UNIQUE KEY uk_task_id (task_id),
    KEY idx_model_time (model_id, create_time),
    KEY idx_provider_time (provider_id, create_time),
    KEY idx_user_time (user_id, create_time),
    KEY idx_status (status)
) COMMENT='AIGC 成本记录';

CREATE TABLE IF NOT EXISTS aigc_recharge_order (
    id bigint NOT NULL AUTO_INCREMENT,
    recharge_no varchar(64) NOT NULL,
    wallet_id bigint NOT NULL,
    user_id bigint NOT NULL,
    recharge_type varchar(32) NOT NULL,
    pay_amount int NOT NULL DEFAULT 0,
    point_amount decimal(18,6) NOT NULL DEFAULT 0.000000,
    gift_amount decimal(18,6) NOT NULL DEFAULT 0.000000,
    total_point_amount decimal(18,6) NOT NULL DEFAULT 0.000000,
    pay_order_id bigint NULL,
    pay_order_no varchar(64) NULL,
    pay_channel_code varchar(32) NULL,
    status varchar(32) NOT NULL,
    pay_time datetime NULL,
    close_time datetime NULL,
    refund_time datetime NULL,
    operator_id bigint NULL,
    remark varchar(512) NULL,
    creator varchar(64) NULL DEFAULT '',
    create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updater varchar(64) NULL DEFAULT '',
    update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted bit NOT NULL DEFAULT b'0',
    tenant_id bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_recharge_no (recharge_no),
    KEY idx_wallet_time (wallet_id, create_time),
    KEY idx_user_status (user_id, status),
    KEY idx_pay_order_id (pay_order_id),
    KEY idx_status_create_time (status, create_time)
) COMMENT='AIGC 充值订单';
