CREATE TABLE IF NOT EXISTS `aigc_canvas_generation_run` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `project_id` bigint NOT NULL COMMENT '画布项目编号',
  `node_id` varchar(128) NOT NULL COMMENT '画布节点编号',
  `run_id` varchar(128) NOT NULL COMMENT '前端运行编号',
  `task_id` bigint NOT NULL COMMENT '生成任务编号',
  `generate_record_id` bigint DEFAULT NULL COMMENT '生成记录编号',
  `generate_no` varchar(64) DEFAULT NULL COMMENT '生成流水号',
  `node_type` varchar(32) NOT NULL COMMENT '节点类型',
  `generate_type` varchar(32) NOT NULL COMMENT '生成类型',
  `generate_mode` varchar(64) NOT NULL COMMENT '生成模式',
  `creator_user_id` bigint NOT NULL COMMENT '创建用户编号',
  `status` varchar(32) NOT NULL COMMENT '运行状态',
  `progress` tinyint DEFAULT NULL COMMENT '进度',
  `op_id` varchar(160) DEFAULT NULL COMMENT '终态操作幂等编号',
  `started_at` datetime NOT NULL COMMENT '开始时间',
  `finished_at` datetime DEFAULT NULL COMMENT '完成时间',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_canvas_generation_run_task` (`task_id`),
  UNIQUE KEY `uk_canvas_generation_run_project_node_task` (`project_id`, `node_id`, `task_id`),
  UNIQUE KEY `uk_canvas_generation_run_project_node_run` (`project_id`, `node_id`, `run_id`),
  UNIQUE KEY `uk_canvas_generation_run_op` (`op_id`),
  KEY `idx_canvas_generation_run_project_node` (`project_id`, `node_id`),
  KEY `idx_canvas_generation_run_project_status` (`project_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AIGC 画布生成运行绑定';
