spring:
  cloud:
    nacos:
      server-addr: 111.228.39.103:8848
      username: nacos
      password: nacos
      discovery:
        namespace: local
        group: DEFAULT_GROUP
        metadata:
          version: 1.0.0
      config:
        encode: UTF-8
        namespace: local
        group: DEFAULT_GROUP

logging:
  level:
    cn.iocoder.yudao.module.aigc.community: debug

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

yudao:
  env:
    tag: ${HOSTNAME}
  security:
    mock-enable: true
  access-log:
    enable: true
