CREATE TABLE IF NOT EXISTS aigc_wallet (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    balance decimal(18,6) NOT NULL DEFAULT 0.000000,
    frozen_balance decimal(18,6) NOT NULL DEFAULT 0.000000,
    total_recharge decimal(18,6) NOT NULL DEFAULT 0.000000,
    total_gift decimal(18,6) NOT NULL DEFAULT 0.000000,
    total_consume decimal(18,6) NOT NULL DEFAULT 0.000000,
    total_refund decimal(18,6) NOT NULL DEFAULT 0.000000,
    status int NOT NULL DEFAULT 0,
    last_trans_time datetime NULL,
    remark varchar(512) NULL,
    creator varchar(64) NULL DEFAULT '',
    create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updater varchar(64) NULL DEFAULT '',
    update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted bit NOT NULL DEFAULT 0,
    tenant_id bigint NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_aigc_wallet_user_tenant ON aigc_wallet(user_id, tenant_id);

CREATE TABLE IF NOT EXISTS aigc_quota_freeze (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    freeze_no varchar(64) NOT NULL,
    wallet_id bigint NOT NULL,
    user_id bigint NOT NULL,
    biz_type varchar(64) NOT NULL,
    biz_id varchar(128) NOT NULL,
    task_id bigint NULL,
    task_no varchar(64) NULL,
    amount decimal(18,6) NOT NULL,
    confirmed_amount decimal(18,6) NOT NULL DEFAULT 0.000000,
    released_amount decimal(18,6) NOT NULL DEFAULT 0.000000,
    status varchar(32) NOT NULL,
    expire_time datetime NULL,
    confirm_time datetime NULL,
    release_time datetime NULL,
    reason varchar(512) NULL,
    creator varchar(64) NULL DEFAULT '',
    create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updater varchar(64) NULL DEFAULT '',
    update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted bit NOT NULL DEFAULT 0,
    tenant_id bigint NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_aigc_quota_freeze_no ON aigc_quota_freeze(freeze_no);
CREATE UNIQUE INDEX IF NOT EXISTS uk_aigc_quota_freeze_biz ON aigc_quota_freeze(biz_type, biz_id, tenant_id);

CREATE TABLE IF NOT EXISTS aigc_billing_record (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    record_no varchar(64) NOT NULL,
    wallet_id bigint NOT NULL,
    user_id bigint NOT NULL,
    biz_type varchar(64) NOT NULL,
    biz_id varchar(128) NOT NULL,
    record_type varchar(64) NOT NULL,
    title varchar(128) NULL,
    amount decimal(18,6) NOT NULL,
    balance_after decimal(18,6) NOT NULL,
    frozen_balance_after decimal(18,6) NOT NULL,
    freeze_id bigint NULL,
    task_id bigint NULL,
    model_id bigint NULL,
    provider_id bigint NULL,
    currency_type varchar(32) NOT NULL DEFAULT 'POINT',
    price_snapshot varchar(4000) NULL,
    extra_info varchar(4000) NULL,
    creator varchar(64) NULL DEFAULT '',
    create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updater varchar(64) NULL DEFAULT '',
    update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted bit NOT NULL DEFAULT 0,
    tenant_id bigint NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_aigc_billing_record_no ON aigc_billing_record(record_no);
CREATE UNIQUE INDEX IF NOT EXISTS uk_aigc_billing_record_biz_tenant ON aigc_billing_record(biz_type, biz_id, tenant_id);

CREATE TABLE IF NOT EXISTS aigc_cost_record (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cost_no varchar(64) NOT NULL,
    task_id bigint NOT NULL,
    task_no varchar(64) NULL,
    user_id bigint NOT NULL,
    model_id bigint NULL,
    provider_id bigint NULL,
    capability varchar(64) NULL,
    billing_unit varchar(32) NULL,
    usage_amount decimal(18,6) NULL,
    cost_amount decimal(18,6) NOT NULL,
    sale_amount decimal(18,6) NOT NULL,
    gross_profit decimal(18,6) NOT NULL,
    gross_profit_rate decimal(18,6) NOT NULL,
    currency_type varchar(32) NOT NULL DEFAULT 'POINT',
    usage_snapshot varchar(4000) NULL,
    price_snapshot varchar(4000) NULL,
    status varchar(32) NOT NULL,
    creator varchar(64) NULL DEFAULT '',
    create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updater varchar(64) NULL DEFAULT '',
    update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted bit NOT NULL DEFAULT 0,
    tenant_id bigint NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_aigc_cost_record_no ON aigc_cost_record(cost_no);
CREATE UNIQUE INDEX IF NOT EXISTS uk_aigc_cost_record_task ON aigc_cost_record(task_id);

CREATE TABLE IF NOT EXISTS aigc_recharge_order (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recharge_no varchar(64) NOT NULL,
    wallet_id bigint NOT NULL,
    user_id bigint NOT NULL,
    recharge_type varchar(32) NOT NULL,
    pay_amount int NOT NULL DEFAULT 0,
    point_amount decimal(18,6) NOT NULL DEFAULT 0.000000,
    gift_amount decimal(18,6) NOT NULL DEFAULT 0.000000,
    total_point_amount decimal(18,6) NOT NULL DEFAULT 0.000000,
    pay_order_id bigint NULL,
    pay_order_no varchar(64) NULL,
    pay_channel_code varchar(32) NULL,
    status varchar(32) NOT NULL,
    pay_time datetime NULL,
    close_time datetime NULL,
    refund_time datetime NULL,
    operator_id bigint NULL,
    remark varchar(512) NULL,
    creator varchar(64) NULL DEFAULT '',
    create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updater varchar(64) NULL DEFAULT '',
    update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted bit NOT NULL DEFAULT 0,
    tenant_id bigint NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_aigc_recharge_order_no ON aigc_recharge_order(recharge_no);
CREATE UNIQUE INDEX IF NOT EXISTS uk_aigc_recharge_order_pay_order_id ON aigc_recharge_order(pay_order_id);

CREATE TABLE IF NOT EXISTS aigc_recharge_package (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(64) NOT NULL,
    pay_amount int NOT NULL DEFAULT 0,
    point_amount decimal(18,6) NOT NULL DEFAULT 0.000000,
    gift_amount decimal(18,6) NOT NULL DEFAULT 0.000000,
    total_point_amount decimal(18,6) NOT NULL DEFAULT 0.000000,
    description varchar(255) NULL,
    features varchar(1000) NULL,
    recommend_status bit NOT NULL DEFAULT 0,
    sort int NOT NULL DEFAULT 0,
    status int NOT NULL DEFAULT 0,
    remark varchar(512) NULL,
    creator varchar(64) NULL DEFAULT '',
    create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updater varchar(64) NULL DEFAULT '',
    update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted bit NOT NULL DEFAULT 0,
    tenant_id bigint NOT NULL DEFAULT 0
);
