CREATE TABLE IF NOT EXISTS `aigc_sensitive_word` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `word` varchar(128) NOT NULL COMMENT '敏感词',
  `scene` varchar(32) NOT NULL COMMENT '审核场景',
  `level` int NOT NULL COMMENT '风险等级',
  `match_type` varchar(32) NOT NULL COMMENT '匹配方式',
  `status` varchar(32) NOT NULL COMMENT '状态',
  `remark` varchar(512) DEFAULT NULL COMMENT '备注',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_scene_word` (`tenant_id`, `scene`, `word`),
  KEY `idx_tenant_scene_status` (`tenant_id`, `scene`, `status`),
  KEY `idx_tenant_level` (`tenant_id`, `level`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AIGC 敏感词表';

CREATE TABLE IF NOT EXISTS `aigc_audit_record` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `object_type` varchar(32) NOT NULL COMMENT '审核对象类型',
  `object_id` bigint NOT NULL COMMENT '审核对象编号',
  `content` text DEFAULT NULL COMMENT '被审核内容',
  `scene` varchar(32) NOT NULL COMMENT '审核场景',
  `audit_status` varchar(32) NOT NULL COMMENT '审核状态',
  `audit_result` varchar(32) DEFAULT NULL COMMENT '审核结果',
  `hit_words` json DEFAULT NULL COMMENT '命中敏感词',
  `risk_level` int NOT NULL DEFAULT 0 COMMENT '风险等级',
  `reject_reason` varchar(512) DEFAULT NULL COMMENT '拒绝原因',
  `auditor_user_id` bigint DEFAULT NULL COMMENT '审核人用户编号',
  `audit_time` datetime DEFAULT NULL COMMENT '审核时间',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_object` (`tenant_id`, `object_type`, `object_id`),
  KEY `idx_tenant_status` (`tenant_id`, `audit_status`, `create_time`),
  KEY `idx_tenant_scene` (`tenant_id`, `scene`, `create_time`),
  KEY `idx_tenant_auditor` (`tenant_id`, `auditor_user_id`, `audit_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AIGC 审核记录表';
