spring:
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        namespace: dev
      config:
        namespace: dev
        file-extension: yaml

  datasource:
    druid:
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true
        allow:
        url-pattern: /druid/*
        login-username: yudao
        login-password: yudao
    dynamic:
      druid:
        initial-size: 1
        min-idle: 1
        max-active: 20
      primary: master
      datasource:
        master:
          url: jdbc:mysql://127.0.0.1:3306/ruoyi-vue-pro?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true&rewriteBatchedStatements=true
          username: root
          password: 123456

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0

xxl:
  job:
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin

logging:
  level:
    cn.iocoder.yudao.module.aigc.asset: debug
