FROM swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/library/eclipse-temurin:21-jre

ARG MODULE_PATH
ARG JAR_NAME

RUN mkdir -p /app
WORKDIR /app
COPY ${MODULE_PATH}/target/${JAR_NAME} app.jar

ENV TZ=Asia/Shanghai JAVA_OPTS="-Xms512m -Xmx512m"

CMD java ${JAVA_OPTS} -Djava.security.egd=file:/dev/./urandom -jar app.jar
