spring:
  application:
    name: gateway-server

  profiles:
    active: dev

  http:
    codecs:
      max-in-memory-size: 10MB

  jackson:
    serialization:
      write-dates-as-timestamps: true
      write-date-timestamps-as-nanoseconds: false
      write-durations-as-timestamps: true
      fail-on-empty-beans: false

  main:
    allow-circular-references: true

  config:
    import:
      - optional:classpath:application-${spring.profiles.active}.yaml
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yaml

  cloud:
    gateway:
      server:
        webflux:
          x-forwarded:
            prefix-enabled: false
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

server:
  port: 48080

logging:
  file:
    name: ${user.home}/logs/${spring.application.name}.log

knife4j:
  gateway:
    enabled: true
--- #################### 芋道相关配置 ####################

yudao:
  info:
    version: 1.0.0
