CREATE TABLE `aigc_task` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `task_no` varchar(64) NOT NULL COMMENT '平台任务编号',
  `client_request_id` varchar(128) DEFAULT NULL COMMENT '客户端请求编号',
  `user_id` bigint NOT NULL COMMENT '用户ID',
  `task_type` varchar(64) NOT NULL COMMENT '任务类型',
  `capability` varchar(64) NOT NULL COMMENT '模型能力',
  `model_id` bigint NOT NULL COMMENT '模型ID',
  `provider_id` bigint DEFAULT NULL COMMENT '渠道商ID',
  `channel_id` bigint DEFAULT NULL COMMENT '渠道实现ID',
  `status` varchar(32) NOT NULL COMMENT '任务状态',
  `progress` int DEFAULT 0 COMMENT '进度',
  `estimated_duration_millis` bigint DEFAULT NULL COMMENT '预计耗时毫秒',
  `request_params` json DEFAULT NULL COMMENT '请求参数快照',
  `price_snapshot` json DEFAULT NULL COMMENT '价格快照',
  `freeze_id` bigint DEFAULT NULL COMMENT '冻结记录ID',
  `sale_price` decimal(18,6) DEFAULT NULL COMMENT '销售价快照',
  `cost_price` decimal(18,6) DEFAULT NULL COMMENT '成本价快照',
  `currency_type` varchar(32) DEFAULT NULL COMMENT '货币类型',
  `external_task_id` varchar(128) DEFAULT NULL COMMENT '第三方任务编号',
  `output_asset_id` bigint DEFAULT NULL COMMENT '输出资产ID',
  `output_asset_type` varchar(32) DEFAULT NULL COMMENT '输出资产类型',
  `output_summary` varchar(1024) DEFAULT NULL COMMENT '输出摘要',
  `fail_code` varchar(128) DEFAULT NULL COMMENT '失败错误码',
  `fail_reason` varchar(1024) DEFAULT NULL COMMENT '失败原因',
  `submit_time` datetime DEFAULT NULL COMMENT '提交时间',
  `start_time` datetime DEFAULT NULL COMMENT '开始执行时间',
  `callback_time` datetime DEFAULT NULL COMMENT '回调时间',
  `finish_time` datetime DEFAULT NULL COMMENT '完成时间',
  `expire_time` datetime DEFAULT NULL COMMENT '超时时间',
  `retry_count` int DEFAULT 0 COMMENT '已重试次数',
  `max_retry_count` int DEFAULT 3 COMMENT '最大重试次数',
  `remark` varchar(512) DEFAULT NULL COMMENT '备注',
  `creator` varchar(64) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) DEFAULT 0 COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_task_no` (`task_no`),
  UNIQUE KEY `uk_client_request` (`tenant_id`, `user_id`, `client_request_id`),
  KEY `idx_tenant_user_deleted_id` (`tenant_id`, `user_id`, `deleted`, `id`),
  KEY `idx_user_status` (`user_id`, `status`),
  KEY `idx_status_create_time` (`status`, `create_time`),
  KEY `idx_external_task_id` (`external_task_id`),
  KEY `idx_model_id` (`model_id`),
  KEY `idx_channel_id` (`channel_id`),
  KEY `idx_tenant_status` (`tenant_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AIGC任务主表';

CREATE TABLE `aigc_task_result` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `task_id` bigint NOT NULL COMMENT '任务ID',
  `output_text` longtext DEFAULT NULL COMMENT '文本输出',
  `output_data` json DEFAULT NULL COMMENT '结构化输出',
  `creator` varchar(64) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) DEFAULT 0 COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_task_id` (`task_id`),
  KEY `idx_tenant_task` (`tenant_id`, `task_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AIGC任务结果表';

CREATE TABLE `aigc_task_log` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `task_id` bigint NOT NULL COMMENT '任务ID',
  `task_no` varchar(64) DEFAULT NULL COMMENT '任务编号',
  `from_status` varchar(32) DEFAULT NULL COMMENT '变更前状态',
  `to_status` varchar(32) DEFAULT NULL COMMENT '变更后状态',
  `action` varchar(64) NOT NULL COMMENT '操作动作',
  `message` varchar(1024) DEFAULT NULL COMMENT '日志消息',
  `operator_type` varchar(32) DEFAULT NULL COMMENT '操作来源类型',
  `operator_id` bigint DEFAULT NULL COMMENT '操作人ID',
  `extra_info` json DEFAULT NULL COMMENT '扩展信息',
  `creator` varchar(64) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) DEFAULT 0 COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  KEY `idx_task_id` (`task_id`),
  KEY `idx_task_no` (`task_no`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AIGC任务日志表';

CREATE TABLE `aigc_task_callback` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `callback_no` varchar(64) NOT NULL COMMENT '回调编号',
  `task_id` bigint DEFAULT NULL COMMENT '任务ID',
  `task_no` varchar(64) DEFAULT NULL COMMENT '任务编号',
  `provider_id` bigint DEFAULT NULL COMMENT '渠道商ID',
  `provider_code` varchar(64) NOT NULL COMMENT '渠道商编码',
  `external_task_id` varchar(128) NOT NULL COMMENT '第三方任务编号',
  `callback_type` varchar(64) NOT NULL COMMENT '回调类型',
  `callback_status` varchar(32) NOT NULL COMMENT '回调处理状态',
  `raw_body` longtext DEFAULT NULL COMMENT '原始回调内容',
  `headers` json DEFAULT NULL COMMENT '请求头摘要',
  `signature` varchar(512) DEFAULT NULL COMMENT '签名',
  `process_result` json DEFAULT NULL COMMENT '处理结果',
  `fail_reason` varchar(1024) DEFAULT NULL COMMENT '处理失败原因',
  `received_time` datetime DEFAULT NULL COMMENT '接收时间',
  `processed_time` datetime DEFAULT NULL COMMENT '处理时间',
  `creator` varchar(64) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) DEFAULT 0 COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_external_callback` (`provider_code`, `external_task_id`, `callback_type`),
  KEY `idx_task_id` (`task_id`),
  KEY `idx_callback_status` (`callback_status`),
  KEY `idx_received_time` (`received_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AIGC任务回调表';

CREATE TABLE `aigc_task_retry` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `retry_no` varchar(64) NOT NULL COMMENT '重试编号',
  `task_id` bigint NOT NULL COMMENT '任务ID',
  `task_no` varchar(64) DEFAULT NULL COMMENT '任务编号',
  `retry_type` varchar(32) DEFAULT NULL COMMENT '重试类型',
  `retry_status` varchar(32) NOT NULL COMMENT '重试状态',
  `retry_count` int DEFAULT 1 COMMENT '第几次重试',
  `next_retry_time` datetime DEFAULT NULL COMMENT '下次重试时间',
  `start_time` datetime DEFAULT NULL COMMENT '开始时间',
  `finish_time` datetime DEFAULT NULL COMMENT '结束时间',
  `fail_reason` varchar(1024) DEFAULT NULL COMMENT '失败原因',
  `operator_id` bigint DEFAULT NULL COMMENT '人工触发人ID',
  `creator` varchar(64) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) DEFAULT 0 COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_retry_no` (`retry_no`),
  KEY `idx_task_id` (`task_id`),
  KEY `idx_retry_status_time` (`retry_status`, `next_retry_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AIGC任务重试表';
