CREATE TABLE IF NOT EXISTS `aigc_community_post` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'Post ID',
  `post_no` varchar(64) NOT NULL COMMENT 'Post number',
  `author_user_id` bigint NOT NULL COMMENT 'Author user ID',
  `asset_id` bigint DEFAULT NULL COMMENT 'Asset ID',
  `asset_type` varchar(32) DEFAULT NULL COMMENT 'Asset type snapshot',
  `project_id` bigint DEFAULT NULL COMMENT 'Canvas project ID',
  `cover_asset_id` bigint DEFAULT NULL COMMENT 'Cover asset ID',
  `title` varchar(128) NOT NULL COMMENT 'Title',
  `summary` varchar(1024) DEFAULT NULL COMMENT 'Summary',
  `tags` varchar(512) DEFAULT NULL COMMENT 'Tags',
  `prompt_snapshot` text COMMENT 'Prompt snapshot',
  `metadata` text COMMENT 'Metadata',
  `visibility` varchar(32) NOT NULL DEFAULT 'PUBLIC' COMMENT 'Visibility',
  `publish_status` varchar(32) NOT NULL COMMENT 'Publish status',
  `audit_status` varchar(32) NOT NULL COMMENT 'Audit status',
  `audit_reason` varchar(512) DEFAULT NULL COMMENT 'Audit reason',
  `auditor_user_id` bigint DEFAULT NULL COMMENT 'Auditor user ID',
  `audit_time` datetime DEFAULT NULL COMMENT 'Audit time',
  `offline_reason` varchar(512) DEFAULT NULL COMMENT 'Offline reason',
  `offline_time` datetime DEFAULT NULL COMMENT 'Offline time',
  `publish_time` datetime DEFAULT NULL COMMENT 'Publish time',
  `view_count` int NOT NULL DEFAULT 0 COMMENT 'View count',
  `like_count` int NOT NULL DEFAULT 0 COMMENT 'Like count',
  `comment_count` int NOT NULL DEFAULT 0 COMMENT 'Visible comment count',
  `share_count` int NOT NULL DEFAULT 0 COMMENT 'Share count',
  `download_count` int NOT NULL DEFAULT 0 COMMENT 'Download count',
  `hot_score` decimal(18,4) NOT NULL DEFAULT 0 COMMENT 'Hot score',
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_post_no` (`post_no`),
  KEY `idx_feed` (`tenant_id`, `publish_status`, `audit_status`, `publish_time`, `id`),
  KEY `idx_hot` (`tenant_id`, `publish_status`, `audit_status`, `hot_score`, `id`),
  KEY `idx_author` (`tenant_id`, `author_user_id`, `publish_status`, `publish_time`),
  KEY `idx_asset_type` (`tenant_id`, `asset_type`, `publish_status`, `audit_status`),
  KEY `idx_asset` (`asset_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AIGC community post';

CREATE TABLE IF NOT EXISTS `aigc_community_post_like` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'Like ID',
  `post_id` bigint NOT NULL COMMENT 'Post ID',
  `user_id` bigint NOT NULL COMMENT 'User ID',
  `status` varchar(32) NOT NULL COMMENT 'FOLLOWING/NORMAL or CANCELLED',
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_post_user` (`tenant_id`, `post_id`, `user_id`),
  KEY `idx_user_status` (`tenant_id`, `user_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AIGC community post like';

CREATE TABLE IF NOT EXISTS `aigc_community_comment` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'Comment ID',
  `post_id` bigint NOT NULL COMMENT 'Post ID',
  `user_id` bigint NOT NULL COMMENT 'User ID',
  `parent_id` bigint NOT NULL DEFAULT 0 COMMENT 'Parent comment ID',
  `content` varchar(1000) NOT NULL COMMENT 'Content',
  `audit_status` varchar(32) NOT NULL COMMENT 'Audit status',
  `audit_reason` varchar(512) DEFAULT NULL COMMENT 'Audit reason',
  `status` varchar(32) NOT NULL COMMENT 'Status',
  `like_count` int NOT NULL DEFAULT 0 COMMENT 'Like count',
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_post_status_time` (`tenant_id`, `post_id`, `status`, `audit_status`, `create_time`),
  KEY `idx_user_time` (`tenant_id`, `user_id`, `create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AIGC community comment';

CREATE TABLE IF NOT EXISTS `aigc_community_share_log` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'Share log ID',
  `post_id` bigint NOT NULL COMMENT 'Post ID',
  `user_id` bigint DEFAULT NULL COMMENT 'User ID',
  `share_channel` varchar(32) DEFAULT NULL COMMENT 'Share channel',
  `share_token` varchar(64) DEFAULT NULL COMMENT 'Share token',
  `client_ip` varchar(64) DEFAULT NULL COMMENT 'Client IP',
  `user_agent` varchar(512) DEFAULT NULL COMMENT 'User agent',
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_post_time` (`tenant_id`, `post_id`, `create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AIGC community share log';

CREATE TABLE IF NOT EXISTS `aigc_community_follow` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'Follow ID',
  `follower_user_id` bigint NOT NULL COMMENT 'Follower user ID',
  `followee_user_id` bigint NOT NULL COMMENT 'Followee user ID',
  `status` varchar(32) NOT NULL COMMENT 'Follow status',
  `follow_time` datetime DEFAULT NULL COMMENT 'Follow time',
  `cancel_time` datetime DEFAULT NULL COMMENT 'Cancel time',
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_follow_pair` (`tenant_id`, `follower_user_id`, `followee_user_id`),
  KEY `idx_followee_status` (`tenant_id`, `followee_user_id`, `status`, `follow_time`),
  KEY `idx_follower_status` (`tenant_id`, `follower_user_id`, `status`, `follow_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AIGC community follow';

CREATE TABLE IF NOT EXISTS `aigc_community_author_stats` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'Stats ID',
  `user_id` bigint NOT NULL COMMENT 'User ID',
  `follower_count` int NOT NULL DEFAULT 0 COMMENT 'Follower count',
  `following_count` int NOT NULL DEFAULT 0 COMMENT 'Following count',
  `public_post_count` int NOT NULL DEFAULT 0 COMMENT 'Public post count',
  `like_received_count` int NOT NULL DEFAULT 0 COMMENT 'Like received count',
  `last_publish_time` datetime DEFAULT NULL COMMENT 'Last publish time',
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user` (`tenant_id`, `user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AIGC community author stats';

CREATE TABLE IF NOT EXISTS `aigc_community_audit_log` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'Audit log ID',
  `object_type` varchar(32) NOT NULL COMMENT 'Object type',
  `object_id` bigint NOT NULL COMMENT 'Object ID',
  `action` varchar(32) NOT NULL COMMENT 'Action',
  `reason` varchar(512) DEFAULT NULL COMMENT 'Reason',
  `operator_user_id` bigint DEFAULT NULL COMMENT 'Operator user ID',
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_object` (`tenant_id`, `object_type`, `object_id`, `create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AIGC community audit log';

CREATE TABLE IF NOT EXISTS `aigc_guide_content` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'Guide content ID',
  `slug` varchar(128) NOT NULL COMMENT 'Stable URL slug',
  `title` varchar(128) NOT NULL COMMENT 'Title',
  `category` varchar(64) DEFAULT NULL COMMENT 'Category',
  `summary` varchar(512) DEFAULT NULL COMMENT 'Summary',
  `content` mediumtext NOT NULL COMMENT 'Markdown content',
  `sort` int NOT NULL DEFAULT 0 COMMENT 'Sort',
  `publish_status` varchar(32) NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT/PUBLISHED',
  `publish_time` datetime DEFAULT NULL COMMENT 'Publish time',
  `publisher_user_id` bigint DEFAULT NULL COMMENT 'Publisher user ID',
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_slug` (`tenant_id`, `slug`),
  KEY `idx_publish_snapshot` (`tenant_id`, `publish_status`, `sort`, `id`),
  KEY `idx_category` (`tenant_id`, `category`, `publish_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AIGC guide content';
