CREATE TABLE IF NOT EXISTS `aigc_asset` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `asset_no` varchar(64) NOT NULL COMMENT '资产编号',
  `user_id` bigint NOT NULL COMMENT '用户 ID',
  `asset_type` varchar(32) NOT NULL COMMENT '资产类型',
  `source_type` varchar(32) NOT NULL COMMENT '来源类型',
  `biz_type` varchar(64) DEFAULT NULL COMMENT '业务类型',
  `biz_id` varchar(128) DEFAULT NULL COMMENT '业务 ID',
  `task_id` bigint DEFAULT NULL COMMENT '来源任务 ID',
  `task_no` varchar(64) DEFAULT NULL COMMENT '来源任务编号',
  `model_id` bigint DEFAULT NULL COMMENT '模型 ID',
  `provider_id` bigint DEFAULT NULL COMMENT '渠道商 ID',
  `title` varchar(255) DEFAULT NULL COMMENT '资产标题',
  `description` varchar(1024) DEFAULT NULL COMMENT '资产描述',
  `tags` varchar(512) DEFAULT NULL COMMENT '标签',
  `width` int DEFAULT NULL COMMENT '宽度',
  `height` int DEFAULT NULL COMMENT '高度',
  `duration` decimal(18,3) DEFAULT NULL COMMENT '时长',
  `metadata` json DEFAULT NULL COMMENT '扩展元数据',
  `prompt_snapshot` json DEFAULT NULL COMMENT '提示词快照',
  `generate_snapshot` json DEFAULT NULL COMMENT '生成参数快照',
  `visibility` varchar(32) NOT NULL COMMENT '可见性',
  `audit_status` varchar(32) NOT NULL COMMENT '审核状态',
  `audit_reason` varchar(512) DEFAULT NULL COMMENT '审核原因',
  `status` varchar(32) NOT NULL COMMENT '状态',
  `view_count` int NOT NULL DEFAULT 0 COMMENT '预览次数',
  `download_count` int NOT NULL DEFAULT 0 COMMENT '下载次数',
  `use_count` int NOT NULL DEFAULT 0 COMMENT '使用次数',
  `last_used_time` datetime DEFAULT NULL COMMENT '最近使用时间',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_asset_no` (`asset_no`),
  KEY `idx_task_type_tenant` (`task_id`, `asset_type`, `tenant_id`),
  KEY `idx_user_type_time` (`user_id`, `asset_type`, `create_time`),
  KEY `idx_task_id` (`task_id`),
  KEY `idx_task_no` (`task_no`),
  KEY `idx_biz` (`biz_type`, `biz_id`),
  KEY `idx_model_id` (`model_id`),
  KEY `idx_audit_status` (`audit_status`),
  KEY `idx_visibility` (`visibility`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AIGC 资产主表';

CREATE TABLE IF NOT EXISTS `aigc_asset_file` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `asset_id` bigint NOT NULL COMMENT '资产 ID',
  `file_role` varchar(32) NOT NULL COMMENT '文件角色',
  `file_id` bigint DEFAULT NULL COMMENT '平台文件 ID',
  `storage_config_id` bigint DEFAULT NULL COMMENT '存储配置 ID',
  `storage_type` varchar(32) DEFAULT NULL COMMENT '存储类型',
  `bucket` varchar(128) DEFAULT NULL COMMENT 'Bucket',
  `object_key` varchar(1024) NOT NULL COMMENT '对象 Key',
  `file_path` varchar(1024) DEFAULT NULL COMMENT '平台文件路径',
  `origin_url` varchar(4096) DEFAULT NULL COMMENT '第三方原始 URL',
  `origin_expire_time` datetime DEFAULT NULL COMMENT '第三方原始 URL 过期时间',
  `file_name` varchar(255) DEFAULT NULL COMMENT '文件名',
  `file_ext` varchar(32) DEFAULT NULL COMMENT '文件扩展名',
  `mime_type` varchar(128) DEFAULT NULL COMMENT 'MIME 类型',
  `file_size` bigint DEFAULT NULL COMMENT '文件大小',
  `etag` varchar(128) DEFAULT NULL COMMENT '对象 ETag',
  `checksum` varchar(128) DEFAULT NULL COMMENT '文件校验值',
  `width` int DEFAULT NULL COMMENT '宽度',
  `height` int DEFAULT NULL COMMENT '高度',
  `duration` decimal(18,3) DEFAULT NULL COMMENT '时长',
  `access_mode` tinyint NOT NULL DEFAULT 1 COMMENT '访问模式：1私有签名 2公开 3CDN公开',
  `public_url` varchar(2048) DEFAULT NULL COMMENT '公开访问 URL',
  `status` varchar(32) NOT NULL COMMENT '状态',
  `metadata` json DEFAULT NULL COMMENT '扩展元数据',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_asset_role` (`asset_id`, `file_role`, `deleted`),
  KEY `idx_asset_id` (`asset_id`),
  KEY `idx_file_id` (`file_id`),
  KEY `idx_object_key` (`object_key`(255)),
  KEY `idx_storage_config_id` (`storage_config_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AIGC 资产文件表';

CREATE TABLE IF NOT EXISTS `aigc_asset_download_log` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `asset_id` bigint NOT NULL COMMENT '资产 ID',
  `asset_no` varchar(64) NOT NULL COMMENT '资产编号',
  `user_id` bigint DEFAULT NULL COMMENT '下载用户 ID',
  `owner_user_id` bigint NOT NULL COMMENT '资产归属用户 ID',
  `download_url` varchar(1024) DEFAULT NULL COMMENT '下载 URL',
  `client_ip` varchar(64) DEFAULT NULL COMMENT '客户端 IP',
  `user_agent` varchar(512) DEFAULT NULL COMMENT 'User-Agent',
  `referer` varchar(512) DEFAULT NULL COMMENT '来源页面',
  `result` varchar(32) NOT NULL COMMENT '下载结果',
  `fail_reason` varchar(512) DEFAULT NULL COMMENT '失败原因',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  KEY `idx_asset_time` (`asset_id`, `create_time`),
  KEY `idx_user_time` (`user_id`, `create_time`),
  KEY `idx_owner_time` (`owner_user_id`, `create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AIGC 资产下载日志表';

CREATE TABLE IF NOT EXISTS `aigc_prompt_template` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `template_no` varchar(64) NOT NULL COMMENT '模板编号',
  `source_type` varchar(32) NOT NULL DEFAULT 'IMPORT' COMMENT '来源类型：IMPORT/USER/OFFICIAL',
  `source_case_id` bigint DEFAULT NULL COMMENT '外部案例 ID',
  `source_repo` varchar(255) DEFAULT NULL COMMENT '来源仓库',
  `source_label` varchar(128) DEFAULT NULL COMMENT '来源作者',
  `source_url` varchar(1024) DEFAULT NULL COMMENT '来源链接',
  `github_url` varchar(1024) DEFAULT NULL COMMENT 'GitHub 原始链接',
  `title` varchar(255) NOT NULL COMMENT '标题',
  `description` varchar(1024) DEFAULT NULL COMMENT '描述',
  `prompt` mediumtext NOT NULL COMMENT '完整提示词',
  `prompt_preview` varchar(1024) DEFAULT NULL COMMENT '提示词摘要',
  `category` varchar(128) DEFAULT NULL COMMENT '分类',
  `styles` json DEFAULT NULL COMMENT '风格标签',
  `scenes` json DEFAULT NULL COMMENT '场景标签',
  `tags` varchar(512) DEFAULT NULL COMMENT '搜索标签',
  `cover_file_id` bigint DEFAULT NULL COMMENT '封面文件 ID',
  `storage_config_id` bigint DEFAULT NULL COMMENT '存储配置 ID',
  `storage_type` varchar(32) DEFAULT NULL COMMENT '存储类型',
  `bucket` varchar(128) DEFAULT NULL COMMENT 'Bucket',
  `object_key` varchar(1024) DEFAULT NULL COMMENT '对象 Key',
  `file_path` varchar(1024) DEFAULT NULL COMMENT '平台文件路径',
  `public_url` varchar(2048) DEFAULT NULL COMMENT '公开访问 URL',
  `width` int DEFAULT NULL COMMENT '图片宽度',
  `height` int DEFAULT NULL COMMENT '图片高度',
  `mime_type` varchar(128) DEFAULT NULL COMMENT 'MIME 类型',
  `file_size` bigint DEFAULT NULL COMMENT '文件大小',
  `access_mode` tinyint NOT NULL DEFAULT 1 COMMENT '访问模式：1私有签名 2公开 3CDN公开',
  `featured` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否推荐',
  `sort` int NOT NULL DEFAULT 0 COMMENT '排序',
  `visibility` varchar(32) NOT NULL DEFAULT 'PUBLIC' COMMENT '可见性',
  `audit_status` varchar(32) NOT NULL DEFAULT 'PASS' COMMENT '审核状态',
  `status` varchar(32) NOT NULL DEFAULT 'NORMAL' COMMENT '状态',
  `view_count` int NOT NULL DEFAULT 0 COMMENT '查看次数',
  `copy_count` int NOT NULL DEFAULT 0 COMMENT '复制次数',
  `use_count` int NOT NULL DEFAULT 0 COMMENT '复用次数',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_template_no` (`template_no`),
  UNIQUE KEY `uk_source_case` (`source_repo`, `source_case_id`, `deleted`),
  KEY `idx_category_status` (`category`, `status`, `sort`),
  KEY `idx_featured_status` (`featured`, `status`, `sort`),
  KEY `idx_cover_file_id` (`cover_file_id`),
  FULLTEXT KEY `ft_title_prompt` (`title`, `prompt`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AIGC 提示词模板库';
